import type { Package } from './types';

/**
 * Fixed price sheet. This file is the single source of truth for package slugs,
 * names and prices. Services, the pricing page and enquiry forms all read from here.
 * Prices are in Mauritian rupees and are confirmed after a short call.
 */

export const PACKAGE_GROUPS: Array<{ key: Package['group']; label: string; blurb: string }> = [
  {
    key: 'websites',
    label: 'Websites',
    blurb:
      'Fixed prices for repairs, refreshes and new sites. You supply the text and photos, I build, test and launch.',
  },
  {
    key: 'support',
    label: 'Care plans',
    blurb:
      'Monthly plans so your site keeps working after launch. Optional, with no fixed-term contract.',
  },
  {
    key: 'software',
    label: 'Software & automation',
    blurb:
      'Integrations, dashboards, AI assistants and custom applications. Larger builds are quoted after a scoping call.',
  },
  {
    key: 'it',
    label: 'IT, security & marketing',
    blurb:
      'Audits, networks, CCTV, phones, repairs, consulting and the basics of getting found online. Hardware is quoted separately.',
  },
];

export const PACKAGES: Package[] = [
  // ---------------------------------------------------------------- websites
  {
    slug: 'site-fix',
    group: 'websites',
    name: 'Website repair & fixes',
    price: 'MUR 8,000',
    priceUnit: 'one-off',
    bestFor: 'You already have a website and a few things on it are broken or wrong.',
    delivery: '3 to 5 working days',
    includes: [
      'Up to three agreed issues fixed, for example broken links or forms, placeholder text, a mobile layout problem, or opening hours and prices that do not match',
      'Small text and image changes on the pages I touch',
      'Contact form tested, including the email it sends you',
      'Check on mobile, tablet and desktop',
      'Short note of what I changed and anything else I noticed',
    ],
    excludes: [
      'New pages or new features',
      'Rewriting content from scratch',
      'Hosting or domain renewals',
    ],
    serviceSlug: 'web-redesign',
  },
  {
    slug: 'site-refresh',
    group: 'websites',
    name: 'Page refresh',
    price: 'MUR 15,000',
    priceUnit: 'one-off',
    bestFor: 'Your site works but the main pages look dated or still carry template wording.',
    delivery: '1 to 2 weeks',
    includes: [
      'Up to three existing pages reworked with your approved text and photos',
      'One enquiry form, rebuilt or added, with email notification to you',
      'Layout and navigation tidied on the pages in scope',
      'Mobile check on every refreshed page',
      'Loading speed checked and obvious slow points fixed',
      'Testing before the pages go live',
    ],
    excludes: [
      'Pages beyond the three agreed',
      'A new design for the whole site',
      'Copywriting, unless agreed separately',
    ],
    serviceSlug: 'web-redesign',
  },
  {
    slug: 'site-starter',
    group: 'websites',
    name: 'Starter website',
    price: 'MUR 20,000',
    priceUnit: 'one-off',
    bestFor: 'A small business or sole trader that needs a clear, professional site and has nothing online yet, or only a Facebook page.',
    delivery: '2 to 3 weeks',
    includes: [
      'Up to four pages, for example home, services, about and contact',
      'Mobile-friendly layout, tested on phones, tablets and desktop',
      'Enquiry form with email notification to you',
      'WhatsApp button on every page',
      'Basic search-engine setup: titles, descriptions, sitemap',
      'Visitor analytics so you can see where enquiries come from',
      'Built from your supplied text, photos and logo',
      'Launch on your domain, with SSL',
    ],
    excludes: [
      'Photography and copywriting',
      'Online payments or bookings',
      'Hosting and domain fees',
    ],
    serviceSlug: 'web-design',
  },
  {
    slug: 'site-business',
    group: 'websites',
    name: 'Business website',
    price: 'MUR 30,000',
    priceUnit: 'one-off',
    bestFor: 'An established business that wants a site to bring in enquiries, quotations or booking requests every week.',
    delivery: '3 to 4 weeks',
    includes: [
      'Up to six pages',
      'Photo gallery with up to 30 items',
      'Structured enquiry, quotation or booking-request form that collects what you actually need, such as dates, group size or dimensions',
      'Automatic acknowledgement email to the customer',
      'WhatsApp button and click-to-call on every page',
      'Search-engine setup and visitor analytics',
      'Simple content-management area so you can update text, photos and prices yourself',
      'Testing on mobile, tablet and desktop before launch',
    ],
    excludes: [
      'Live availability or online payment',
      'Photography and copywriting',
      'Hosting and domain fees',
    ],
    recommended: true,
    serviceSlug: 'web-design',
  },
  {
    slug: 'site-catalogue',
    group: 'websites',
    name: 'Catalogue & quotation site',
    price: 'MUR 35,000',
    priceUnit: 'one-off',
    bestFor: 'Suppliers, wholesalers, furniture makers and trades that sell on quotation rather than at a fixed online price.',
    delivery: '4 to 5 weeks',
    includes: [
      '20 to 30 products or services with photos, descriptions and options',
      'Quotation-request basket: customers pick items, add quantities and send one request',
      'Admin view where you see and manage the requests',
      'Email notification to you and acknowledgement to the customer',
      'WhatsApp button on every page',
      'Search-engine setup and visitor analytics',
      'Content-management area for adding and editing products',
    ],
    excludes: [
      'Live stock levels',
      'Online payments (see Online store)',
      'Product photography',
    ],
    serviceSlug: 'ecommerce',
  },
  {
    slug: 'site-ecommerce',
    group: 'websites',
    name: 'Online store',
    price: 'From MUR 55,000',
    priceUnit: 'one-off',
    priceNote: 'Final price confirmed after a scoping call',
    bestFor: 'You want customers to order and pay online, with delivery or pick-up handled on the site.',
    delivery: '5 to 8 weeks',
    includes: [
      'Product catalogue with categories, variants and stock',
      'Cart and checkout',
      'Payment gateway: MIPS, Stripe or PayPal, depending on what you can open',
      'Order notifications to you and confirmation emails to the customer',
      'Delivery and pick-up options with your own rules',
      'Admin area for products, orders and customers',
      'Search-engine setup and analytics',
      'Testing of the full order journey before launch',
    ],
    excludes: [
      'Payment-gateway fees and account opening',
      'Product photography and descriptions',
      'Accounting or courier integrations, quoted separately',
    ],
    serviceSlug: 'ecommerce',
  },

  // ----------------------------------------------------------------- support
  {
    slug: 'care-basic',
    group: 'support',
    name: 'Care plan · Basic',
    price: 'MUR 1,500',
    priceUnit: 'per month',
    bestFor: 'A small site that changes rarely but should not be left unattended.',
    delivery: 'Ongoing, monthly',
    includes: [
      'Routine checks that the site is up and loading',
      'Regular backups, kept off the hosting server',
      'Contact form tested every month',
      'Up to two small text or image updates per month',
      'Email support, reply within one business day',
    ],
    excludes: [
      'Development work or new features',
      'Hosting and domain fees',
    ],
    serviceSlug: 'web-design',
  },
  {
    slug: 'care-standard',
    group: 'support',
    name: 'Care plan · Standard',
    price: 'MUR 2,500',
    priceUnit: 'per month',
    bestFor: 'A business site that brings in enquiries and needs someone to call when something breaks.',
    delivery: 'Ongoing, monthly',
    includes: [
      'Everything in Basic',
      'Technical troubleshooting when something stops working',
      'Minor changes to existing content, for example prices, hours, team members, photos',
      'Monthly summary of what was done and how the site is performing',
      'Reply within one business day, by WhatsApp or email',
    ],
    excludes: [
      'New pages, features or integrations',
      'Hosting and domain fees',
    ],
    recommended: true,
    serviceSlug: 'web-design',
  },
  {
    slug: 'care-plus',
    group: 'support',
    name: 'Care plan · Plus',
    price: 'MUR 4,000',
    priceUnit: 'per month',
    bestFor: 'A site or web application your business depends on daily, where downtime costs you money.',
    delivery: 'Ongoing, monthly',
    includes: [
      'Everything in Standard',
      'Up to four hours of development changes per month',
      'Uptime monitoring with alerts to me, so I usually know before you do',
      'Security updates and periodic vulnerability checks',
      'Quarterly review call to plan what to improve next',
    ],
    excludes: [
      'Work beyond four hours in a month, quoted separately',
      'Hosting and domain fees',
    ],
    serviceSlug: 'web-design',
  },

  // ---------------------------------------------------------------- software
  {
    slug: 'automation-workflow',
    group: 'software',
    name: 'Enquiry & admin automation',
    price: 'MUR 25,000',
    priceUnit: 'one-off',
    priceNote: 'Optional support MUR 3,500 per month',
    bestFor: 'You or your staff retype the same enquiry into WhatsApp, email and a spreadsheet, and things get missed.',
    delivery: '2 to 3 weeks',
    includes: [
      'One workflow connecting two systems, for example website form to WhatsApp, email and a Google Sheet',
      'Automatic acknowledgement to the customer',
      'Staff notifications with the details they need to act',
      'Simple log so you can see what was sent and when',
      'Testing with real sample enquiries before go-live',
      'Short written guide for your team',
    ],
    excludes: [
      'Additional workflows or systems, quoted separately',
      'Paid subscriptions for third-party tools',
    ],
    serviceSlug: 'automation-ai',
  },
  {
    slug: 'booking-integration',
    group: 'software',
    name: 'Booking or payment integration',
    price: 'MUR 30,000',
    priceUnit: 'one-off',
    priceNote: 'Optional support MUR 3,000 per month',
    bestFor: 'You already use a booking tool or want to take payments, and it needs to work properly on your website.',
    delivery: '2 to 4 weeks',
    includes: [
      'Connect one existing booking tool or one payment gateway to your website',
      'Booking or payment flow embedded so customers do not leave your site',
      'Confirmation emails and notifications to your team',
      'Your team keeps control of confirming availability and prices',
      'Testing of the full journey, including failed and cancelled payments',
      'Handover notes',
    ],
    excludes: [
      'Gateway or booking-tool subscription fees',
      'Building a booking system from scratch (see Custom application)',
    ],
    serviceSlug: 'software-development',
  },
  {
    slug: 'dashboard',
    group: 'software',
    name: 'Business dashboard',
    price: 'MUR 40,000',
    priceUnit: 'one-off',
    priceNote: 'Optional support MUR 4,000 per month',
    bestFor: 'You make decisions from spreadsheets that someone updates by hand, and you want the numbers in one place.',
    delivery: '3 to 5 weeks',
    includes: [
      'Reporting dashboard built from one approved data source, such as a spreadsheet, database or export',
      'Data validation so bad entries are flagged rather than hidden',
      'Agreed set of charts and tables, viewable on phone and desktop',
      'Login for your team, with view-only access where needed',
      'Scheduled refresh of the data',
      'Walkthrough session with the people who will use it',
    ],
    excludes: [
      'Additional data sources, quoted separately',
      'Cleaning years of historical data by hand',
    ],
    serviceSlug: 'software-development',
  },
  {
    slug: 'ai-assistant',
    group: 'software',
    name: 'AI assistant pilot',
    price: 'MUR 45,000',
    priceUnit: 'one-off',
    priceNote: 'Optional support MUR 5,000 per month',
    bestFor: 'You get the same questions on WhatsApp or your website all day and want faster replies without losing control of what is said.',
    delivery: '4 to 6 weeks',
    includes: [
      'WhatsApp or website assistant that answers only from content you have approved',
      'Staff-reviewed mode to start: the assistant drafts, your team sends',
      'Escalation to a human when the question is outside scope',
      'Conversation log your team can review',
      'Approved-content pack set up with you, and easy to update',
      'Four weeks of pilot monitoring with a written summary at the end',
    ],
    excludes: [
      'WhatsApp Business API and AI provider usage fees',
      'Bookings or payments inside the chat, quoted separately',
    ],
    recommended: true,
    serviceSlug: 'automation-ai',
  },
  {
    slug: 'custom-app',
    group: 'software',
    name: 'Custom application',
    price: 'From MUR 80,000',
    priceUnit: 'one-off',
    priceNote: 'Scoped quote after a requirements session',
    bestFor: 'Your process has outgrown spreadsheets and off-the-shelf tools, and you need software built around how you work.',
    delivery: '6 to 12 weeks',
    includes: [
      'Requirements sessions and a written scope you sign off before build',
      'Portals, inventory, quotation, booking or internal tools, built in React, NestJS or .NET',
      'Database design, user roles and access control',
      'Testing with your team on real cases before launch',
      'Deployment to your cloud or hosting, with backups configured',
      'Documentation, training and handover',
      'You own the code and the data',
    ],
    excludes: [
      'Hosting, licences and third-party fees',
      'Features added after sign-off, quoted as a change',
    ],
    serviceSlug: 'software-development',
  },
  {
    slug: 'mobile-app',
    group: 'software',
    name: 'Mobile app (Android & iOS)',
    price: 'From MUR 120,000',
    priceUnit: 'one-off',
    priceNote: 'Scoped quote after a requirements session',
    bestFor: 'You need an app your customers or staff will use daily, on both Android and iPhone, from one codebase.',
    delivery: '8 to 14 weeks',
    includes: [
      'One Flutter codebase for Android and iOS',
      'Written scope and screen list agreed before build',
      'Backend API and admin area where the app needs them',
      'Login, notifications and offline handling as agreed',
      'Testing on real devices',
      'Publishing to Google Play and the App Store under your accounts',
      'Handover of source code and store access',
    ],
    excludes: [
      'Apple and Google developer account fees',
      'Ongoing store maintenance, available on a monthly plan',
    ],
    serviceSlug: 'mobile-apps',
  },

  // ---------------------------------------------------------------------- it
  {
    slug: 'security-audit',
    group: 'it',
    name: 'Security & website audit',
    price: 'MUR 12,000',
    priceUnit: 'one-off',
    bestFor: 'You are not sure how exposed your business is and want a straight answer before something goes wrong.',
    delivery: '1 week',
    includes: [
      'Firewall and network configuration review',
      'Email security check: SPF, DKIM, DMARC and account protection',
      'Website scan for known vulnerabilities and outdated components',
      'Backup review: what is backed up, where, and whether it restores',
      'Staff-device review: updates, antivirus, password practice',
      'Written report with fixes ranked by urgency and cost',
      'Follow-up call to go through the findings',
    ],
    excludes: [
      'Carrying out the fixes, quoted separately from the report',
      'Formal penetration testing or compliance certification',
    ],
    serviceSlug: 'cyber-security',
  },
  {
    slug: 'cloud-review',
    group: 'it',
    name: 'Cloud cost & backup review',
    price: 'MUR 12,000',
    priceUnit: 'one-off',
    priceNote: 'Optional monitoring MUR 3,500 per month',
    bestFor: 'Your hosting or cloud bill keeps growing and nobody has checked whether the backups actually work.',
    delivery: '1 week',
    includes: [
      'Review of your Azure, hosting or cloud accounts and what you pay for',
      'List of unused or oversized resources with the saving for each',
      'Backup and recovery check, including a test restore where possible',
      'Recommendations on Cloudflare, DNS and SSL where relevant',
      'Written report with actions in priority order',
    ],
    excludes: [
      'Implementing the changes, quoted separately',
      'Cloud provider charges',
    ],
    serviceSlug: 'cloud-devops',
  },
  {
    slug: 'network-setup',
    group: 'it',
    name: 'Office network & firewall',
    price: 'From MUR 25,000',
    priceUnit: 'one-off',
    priceNote: 'Hardware quoted separately',
    bestFor: 'A new office, a move, or a network that has grown by adding cables and nobody knows how it works.',
    delivery: '1 to 3 weeks, depending on hardware lead time',
    includes: [
      'Fortinet firewall configuration: rules, web filtering, VPN for remote staff',
      'Cisco Catalyst switch configuration',
      'Wi-Fi design and setup, with separate guest network',
      'VLANs to keep cameras, guests, tills and office machines apart',
      'Site-to-site or remote-access VPN',
      'Network diagram and documentation you keep',
      'Handover session with whoever looks after IT on your side',
    ],
    excludes: [
      'Firewall, switches, access points and cabling',
      'Internet subscription',
    ],
    serviceSlug: 'network-infrastructure',
  },
  {
    slug: 'cctv',
    group: 'it',
    name: 'CCTV & remote viewing',
    price: 'From MUR 15,000',
    priceUnit: 'one-off',
    priceNote: 'Cameras and recorder quoted separately',
    bestFor: 'Shops, workshops, guesthouses and yards that want continuous recording and a live view on the phone.',
    delivery: '1 to 2 weeks',
    includes: [
      'Camera placement plan based on a site visit',
      'Hikvision or Dahua system configuration',
      'Recorder set up with agreed retention period',
      'Mobile viewing on your phone, secured properly rather than with default passwords',
      'Cameras isolated on their own network segment',
      'Short guide for finding and exporting footage',
    ],
    excludes: [
      'Cameras, recorder, storage and cabling',
      'Physical installation at height, arranged with an installer if needed',
    ],
    serviceSlug: 'cctv-telephony-iot',
  },
  {
    slug: 'telephony',
    group: 'it',
    name: '3CX phone system',
    price: 'From MUR 20,000',
    priceUnit: 'one-off',
    bestFor: 'You miss calls, or staff use personal mobiles for business, and you want one system that follows them.',
    delivery: '1 to 2 weeks',
    includes: [
      '3CX setup, cloud or on-site',
      'Extensions for each user and department',
      'Call routing, queues, voicemail and opening-hours rules',
      'Mobile app so staff take business calls anywhere',
      'WhatsApp and CRM integration where your tools support it',
      'Testing of inbound and outbound calls before cut-over',
      'Staff briefing',
    ],
    excludes: [
      'SIP trunk, numbers and call charges',
      'Desk phones and headsets',
    ],
    serviceSlug: 'cctv-telephony-iot',
  },
  {
    slug: 'it-support',
    group: 'it',
    name: 'IT support retainer',
    price: 'MUR 6,000',
    priceUnit: 'per month',
    bestFor: 'A team of up to ten people with no in-house IT and a growing list of small problems.',
    delivery: 'Ongoing, monthly',
    includes: [
      'Remote support for up to 10 users, by WhatsApp, phone or remote session',
      'One on-site visit per month',
      'Windows, Office and application updates',
      'Backup checks',
      'New-user setup and leaver clean-up',
      'Reply within one business day, sooner for anything that stops work',
      'Monthly note of what was done',
    ],
    excludes: [
      'Hardware, licences and parts',
      'Projects such as a new network or migration, quoted separately',
    ],
    recommended: true,
    serviceSlug: 'it-support-repairs',
  },
  {
    slug: 'repair',
    group: 'it',
    name: 'Computer repair & tune-up',
    price: 'From MUR 1,500',
    priceUnit: 'per device',
    priceNote: 'Parts quoted before any purchase',
    bestFor: 'A slow, crashing or infected laptop or desktop, or one that will not start.',
    delivery: '1 to 3 days',
    includes: [
      'Diagnosis and a clear quote before I start',
      'Clean-up of malware, start-up clutter and unused software',
      'Upgrades: SSD, RAM, battery',
      'Data recovery attempt from failing drives',
      'Windows reinstall and setup, with your files and printers back where they were',
      'New-machine setup and transfer from the old one',
    ],
    excludes: [
      'Parts',
      'Board-level repairs, referred to a specialist',
    ],
    serviceSlug: 'it-support-repairs',
  },
  {
    slug: 'consulting',
    group: 'it',
    name: 'IT consulting day',
    price: 'MUR 15,000',
    priceUnit: 'per day',
    priceNote: 'Half day MUR 8,000',
    bestFor: 'You need an experienced engineer in the room for a decision, a stuck project or a supplier conversation.',
    delivery: 'Booked by the day',
    includes: [
      'Requirements gathering with your team',
      'Architecture and technology choices explained in plain terms',
      'Vendor and quotation review, so you know what you are signing',
      'Project rescue: where a build has stalled and what to do about it',
      'Written recommendations after the session',
      'Remote or on-site in Mauritius',
    ],
    excludes: [
      'Implementation work, quoted separately',
      'Travel outside Mauritius',
    ],
    serviceSlug: 'it-consulting',
  },
  {
    slug: 'ai-workshop',
    group: 'it',
    name: 'Practical AI workshop',
    price: 'MUR 8,000',
    priceUnit: 'per session',
    bestFor: 'A small team that wants to use AI tools in daily work without leaking customer data or trusting wrong answers.',
    delivery: 'Half-day session',
    includes: [
      'Hands-on session for a small team, at your premises or online',
      'Worked examples from your own tasks: emails, quotes, reports, spreadsheets',
      'Rules for safe use: what to share, what to check, what to never paste',
      'Short list of tools worth paying for, and which are not',
      'One-page guide your team keeps',
    ],
    excludes: [
      'Tool subscriptions',
      'Building automations, quoted as a project',
    ],
    serviceSlug: 'automation-ai',
  },
  {
    slug: 'seo-starter',
    group: 'it',
    name: 'SEO & Google Business setup',
    price: 'MUR 10,000',
    priceUnit: 'one-off',
    bestFor: 'You have a website but customers searching for what you do in your area do not find you.',
    delivery: '1 to 2 weeks, then one month of monitoring',
    includes: [
      'Google Business Profile set up or cleaned up, with photos, hours and services',
      'On-page SEO: titles, descriptions, headings and image text on your existing pages',
      'Google Search Console and analytics connected',
      'Sitemap submitted and indexing problems fixed',
      'One month of monitoring with a short report at the end',
      'Plain list of what to do next',
    ],
    excludes: [
      'Paid advertising',
      'Ongoing content writing',
    ],
    serviceSlug: 'marketing-growth',
  },
  {
    slug: 'whatsapp-business',
    group: 'it',
    name: 'WhatsApp Business setup',
    price: 'MUR 12,000',
    priceUnit: 'one-off',
    bestFor: 'Most of your customers already message you on WhatsApp and you want it organised rather than one long thread on a personal phone.',
    delivery: '1 week',
    includes: [
      'WhatsApp Business account set up with profile, hours and location',
      'Catalogue of your products or services with photos and prices',
      'Quick replies for the questions you answer every day',
      'Greeting and away messages',
      'Click-to-chat links and buttons on your website and social pages',
      'Labels for tracking enquiries, orders and follow-ups',
      'Staff briefing',
    ],
    excludes: [
      'WhatsApp Business API and automated assistants (see AI assistant pilot)',
    ],
    serviceSlug: 'marketing-growth',
  },
  {
    slug: 'content-pack',
    group: 'it',
    name: 'Promo design pack',
    price: 'MUR 2,500',
    priceUnit: 'one-off',
    priceNote: 'Optional MUR 6,500 per month for eight designs with captions and scheduling',
    bestFor: 'You need a poster, a promotion or a menu that looks professional, and you need it this week.',
    delivery: '2 to 3 working days',
    includes: [
      'Three layouts, for example a poster, a social post and a story or flyer',
      'Your logo, colours and photos used throughout',
      'Two rounds of changes',
      'Files sized for print and for Facebook, Instagram and WhatsApp',
      'Monthly option: eight designs a month with captions written and posts scheduled',
    ],
    excludes: [
      'Printing',
      'Logo design, quoted separately',
    ],
    serviceSlug: 'marketing-growth',
  },
];

export const STANDARD_TERMS: Array<{ title: string; body: string }> = [
  {
    title: 'Scope agreed in writing',
    body: 'Before any work starts, you get a short written scope with what is included, what is not, the price and the timeline. Nothing begins until you have approved it.',
  },
  {
    title: '50% to begin, 50% on approval',
    body: 'Half the fee starts the work. The other half is due once you have reviewed and approved the result, before launch or handover.',
  },
  {
    title: 'Third-party costs are separate',
    body: 'Hosting, domain names, payment gateways, hardware and paid services are charged separately, and only with your approval.',
  },
  {
    title: 'New features quoted separately',
    body: 'If you want something added after the scope is agreed, I quote it as a change so there are no surprises on the invoice.',
  },
  {
    title: 'You own everything',
    body: 'Code, content, accounts and data belong to you. You get the source and the logins at handover, and you can take the work to anyone else at any time.',
  },
  {
    title: 'Reply within one business day',
    body: 'I answer messages within one business day, by WhatsApp or email. On care plans and support retainers, anything that stops work gets priority.',
  },
];

export const PRICING_NOTES: string[] = [
  'Fixed-price packages cost what is listed. Packages marked "from" are confirmed after a short call, once I have seen your existing site, systems or premises.',
  'Hardware such as firewalls, switches, cameras, phones and parts is quoted separately, and only bought once you have approved the quote.',
  'Larger projects can be split into phases, each with its own scope, price and payment, so you can start small and extend once the first phase is delivered.',
];

export function getPackage(slug: string): Package | undefined {
  return PACKAGES.find((p) => p.slug === slug);
}
